POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Matti Luukkainen1",
  "dateOfBirth": "1971-04-20",
  "ssn": "090471-8888",
  "gender": "male",
  "occupation": "Digital evangelist"
}

###
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
 "date":"2019-08-05",
 "type":"OccupationalHealthcare",
 "specialist":"MD House",
 "employerName":"HyPD",
 "diagnosisCodes":["Z57.1","Z74.3","M51.2"],
 "description":"Patient mistakenly found himself in a nuclear plant waste site without protection gear. Very minor radiation poisoning. ",
 "sickLeave":{"startDate":"2019-08-05","endDate":"2019-08-28"}
}

###
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
 "date":"2019-05-01",
 "specialist":"Dr Byte House",
 "type":"HealthCheck",
 "description":"Digital overdose, very bytestatic. Otherwise healthy.",
 "healthCheckRating":0
}

###
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
 "date":"2015-01-02",
 "type":"Hospital",
 "specialist":"MD House",
 "diagnosisCodes":["S62.5"],
 "description":"Healing time appr. 2 weeks. patient doesn't remember how he got the injury.",
 "discharge":{
  "date":"2015-01-16",
  "criteria":"Thumb has healed."
  }
}

