POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0NGNiZDEwNTcyOWQxNzg3NmM5NzlkNSIsImlhdCI6MTY4Mzg2MDY5NiwiZXhwIjoxNjgzODY0Mjk2fQ.V-HHno8aP2VBirQTElpUazlG9PuDFFDTmDRRcWp8UMs

{
  "title":"title by test",
  "author": "third test",
  "url":"test@test.com",
  "userId": "644cbd105729d17876c979d5",
  "likes": "true"
}
###
GET http://localhost:3001/api/blogs


###
GET http://localhost:3001/api/blogs/644cbd315729d17876c979da

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "test12",
  "name": "tes12 name",
  "password": "test12"
}

###
GET http://localhost:3001/api/users 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0NGNiZDEwNTcyOWQxNzg3NmM5NzlkNSIsImlhdCI6MTY4MzAxNDE1NCwiZXhwIjoxNjgzMDE3NzU0fQ.Ukq88ot2FacKwXtVr_n6xYZiR2wgVdLCwJ_9lephrhM


###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}
###
DELETE http://localhost:3001/api/blogs/6450cda3e211b43e07178b14
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0NGNiZDEwNTcyOWQxNzg3NmM5NzlkNSIsImlhdCI6MTY4MzA4Mzc3NywiZXhwIjoxNjgzMDg3Mzc3fQ.QxIaXp9yRtGNEY-5HLhEnQo3bH9kdVGRKHSrndBOd_s

###
PUT http://localhost:3003/api/blogs/645365671c46c7fad3c79e09
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0NGNiZDEwNTcyOWQxNzg3NmM5NzlkNSIsImlhdCI6MTY4MzE5MDY3MSwiZXhwIjoxNjgzMTk0MjcxfQ.V9QGImhA_h1_hJINeIdgdhJz53kYAbbeXRoioC1hvE0

{
  "likes":"false"
}