POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMiIsImlkIjoiNjQ1ZGFkYzQ3MzhkZWIxY2YxNjIzNGRkIiwiaWF0IjoxNjg0NDg1NDUxLCJleHAiOjE2ODQ0ODkwNTF9.tuH6zFYljpc9BgQWhMQ5eIjQGm1sP7PPnn8f3_we3pg

{
  "title":"title by test12",
  "author": "author is ther12",
  "url":"test@test.com",
  "userId": "645dadc4738deb1cf16234dd",
  "likes": "true"
}
###
GET http://localhost:3003/api/blogs


###
GET http://localhost:3001/api/blogs/644cbd315729d17876c979da

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "test12",
  "name": "tes12 name",
  "password": "test12"
}

###
GET http://localhost:3003/api/users 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0NGNiZDEwNTcyOWQxNzg3NmM5NzlkNSIsImlhdCI6MTY4NDQ4MDYwNiwiZXhwIjoxNjg0NDg0MjA2fQ.1CxSw_44xGEubrouQuywjhMvPQA7uzwuBmRH8K1SduU



###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "test12",
  "password": "test12"
}
###
DELETE http://localhost:3003/api/blogs/64673b98ee9fe004ad40a9a7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMiIsImlkIjoiNjQ1ZGFkYzQ3MzhkZWIxY2YxNjIzNGRkIiwiaWF0IjoxNjg0NDg1NDUxLCJleHAiOjE2ODQ0ODkwNTF9.tuH6zFYljpc9BgQWhMQ5eIjQGm1sP7PPnn8f3_we3pg

###
PUT http://localhost:3003/api/blogs/645365671c46c7fad3c79e09
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0NGNiZDEwNTcyOWQxNzg3NmM5NzlkNSIsImlhdCI6MTY4NDQ4MDYwNiwiZXhwIjoxNjg0NDg0MjA2fQ.1CxSw_44xGEubrouQuywjhMvPQA7uzwuBmRH8K1SduU

{
  "likes":"false"
}